server: 
  port: 8080

spring:
  application:
    name: portal
  
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.wjrabyrmhymwtvcjywea
    password: vAVvcvopZlv2m4N9
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

gemini:
  api-key: "AQ.Ab8RN6Iawgtoym2mMhXx4WROWJJfEr7k2zaoERl9MsuIRHlNJA"